apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: easyvideotrans
resources:
  - easyvideotrans-frontend.ingressroute.yaml
  - easyvideotrans-frontend.service.yaml
  - easyvideotrans-frontend.yaml
  - easyvideotrans-pv-pvc.yaml
  - easyvideotrans-workloads.yaml
  - easyvideotrans.ingressroute.yaml
  - easyvideotrans.namespace.yaml
  - easyvideotrans.service.yaml
  - easyvideotrans.yaml

secretGenerator:
  - name: easyvideotrans-secrets
    files:
      - openai-api-key=secrets/open-ai.key
