name: Pytvzhen-web Docker PR Build

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build EasyVideoTrans service
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false
        tags: hanfa/easyvideotrans:${{github.event.pull_request.number}}

    - name: Build EasyVideoTrans workloads
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile-gpu-workload
        push: false
        tags: hanfa/easyvideotrans-workloads:${{github.event.pull_request.number}}
