name: EasyVideoTrans application test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.12.3
        uses: actions/setup-python@v2
        with:
          python-version: 3.12.3
      - name: Setup git
        uses: actions4git/setup-git@v1
      - name: Verify Git installation
        run: git --version
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 .
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install PyTest
        run: pip install pytest
      - name: Run all EasyVideoTrans tests
        run: pytest .
